name: API CI

on:
  push:
    branches: [ main, develop, '**/*' ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check apps/api

      - name: Type-check (mypy)
        run: |
          pip install mypy
          mypy apps/api --config-file pyproject.toml

      - name: Tests (pytest)
        run: |
          pip install -r apps/api/requirements-dev.txt
          pytest -q apps/api/tests
