name: API CI

on:
  push:
    paths:
      - 'repo/apps/api/**'
      - 'repo/package.json'
      - '.github/workflows/api-ci.yml'
  pull_request:
    paths:
      - 'repo/apps/api/**'
      - 'repo/package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm -C repo/apps/api ci || npm -C repo/apps/api install
      - name: Lint
        run: npm -C repo/apps/api run lint --if-present
      - name: Test
        run: npm -C repo/apps/api test --if-present
      - name: Build
        run: npm -C repo/apps/api run build --if-present
